#!/usr/bin/env python3                                                                                                                                                                                                                                                                                                                                                                                                                                                      
import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
import kong_pdk.pdk.kong as kong                                                                                                                                                                                                                                                                                                                                                                                                                                            
from lxml import etree                                                                                                                                                                                                                                                                                                                                                                                                                                                      
from io import BytesIO                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
import sys                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
sys.path.append("/usr/local/kong/python/lib")                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
Schema = (                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    { "XPath": {"type": "string", "required": False} },                                                                                                                                                                                                                                                                                                                                                                                                                     
    { "Condition": {"type": "string", "required": False} },                                                                                                                                                                                                                                                                                                                                                                                                                 
    { "Upstream": {"type": "string", "required": False} },  
    { "Path": {"type": "string", "required": False} },                                                                                                                                                                                                                                                                                                                                                                                                                  
)                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
version = '1.1.0'                                                                                                                                                                                                                                                                                                                                                                                                                                                           
priority = 30                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
class Route-by-XPath:                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    def __init__(self, config):                                                                                                                                                                                                                                                                                                                                                                                                                                             
        self.config = config                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    #---------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                      
    # Replace the value of XPath tags                                                                                                                                                                                                                                                                                                                                                                                                                                       
    #---------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                      
    def Routing (self, kong):                                                                                                                                                                                                                                                                                                                                                                                                                                          
        kong.log.notice("XPathRouting *** BEGIN ***")                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        # Get XPath to validate condition and do dynamic routing                                                                                                                                                                                                                                                                                                                                                                                                            
        XPath = ""                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        Condition = ""                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        Upstream = ""                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        try:                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            if 'XPath' in self.config:                                                                                                                                                                                                                                                                                                                                                                                                                                      
                XPath = self.config['XPath']                                                                                                                                                                                                                                                                                                                                                                                                                                
            if 'Condition' in self.config:                                                                                                                                                                                                                                                                                                                                                                                                                                  
                Condition = self.config['Condition']                                                                                                                                                                                                                                                                                                                                                                                                                        
            if 'Upstream' in self.config:                                                                                                                                                                                                                                                                                                                                                                                                                                   
                Upstream = self.config['Upstream']                                                                                                                                                                                                                                                                                                                                                                                                                          
            if 'Path' in self.config:                                                                                                                                                                                                                                                                                                                                                                                                                                   
                Path = self.config['Path']                                                                                                                                                                                                                                                                                                                                                                                                                                 
        except:                                                                                                                                                                                                                                                                                                                                                                                                                                                             
            return                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        kong.log.notice("Param XPath : ", XPath)                                                                                                                                                                                                                                                                                                                                                                                                                            
        kong.log.notice("Param Condition : ", Condition)                                                                                                                                                                                                                                                                                                                                                                                                                    
        kong.log.notice("Param Upstream : ", Upstream)   
        kong.log.notice("Param Path : ", Path)                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        # If we don't have the same number of parameters of 'XPathReplace' and 'XPathReplaceValue' we return an Error                                                                                                                                                                                                                                                                                                                                                       
        if XPath == "" or Condition == "" or Upstream == "":                                                                                                                                                                                                                                                                                                                                                                                                                
            kong.log.notice("No routing rule configured, so there is nothing to do")                                                                                                                                                                                                                                                                                                                                                                                        
            return                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        soapEnvelope = ""                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        try:                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            soapEnvelope = kong.request.get_raw_body()                                                                                                                                                                                                                                                                                                                                                                                                                      
        except Exception as ex:                                                                                                                                                                                                                                                                                                                                                                                                                                             
            kong.log.err("Unable to get raw body from request, exception={}".format(ex))                                                                                                                                                                                                                                                                                                                                                                                    
            msgError = "{}".format(ex)                                                                                                                                                                                                                                                                                                                                                                                                                                      
            return kong.response.exit(400, {"XPath replacement failed": msgError})                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        kong.log.notice("SOAP body= ", soapEnvelope)                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        try:                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            treeSOAP = etree.parse(BytesIO(soapEnvelope))                                                                                                                                                                                                                                                                                                                                                                                                                   
            rootSOAP = treeSOAP.getroot()                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
            XpathValue = rootSOAP.find(XPath.strip()).text                                                                                                                                                                                                                                                                                                                                                                                                                  
            kong.log.notice("XPath value compared : ", XpathValue)                                                                                                                                                                                                                                                                                                                                                                                                          
            if XpathValue == Condition:                                                                                                                                                                                                                                                                                                                                                                                                                                     
                kong.log.notice("Condition validated")                                                                                                                                                                                                                                                                                                                                                                                                                      
                kong.service.set_upstream(Upstream)
                if Path != "" :                                                                                                                                                                                                                                                                                                                                                                                                                
                    kong.service.request.set_path(Path)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                #kong.service.request.set_path("/faculty/fawcett/Handouts/cse775/code/calcWebService/Calc.asmx")                                                                                                                                                                                                                                                                                                                                                             
                kong.log.notice("upstream changed")                                                                                                                                                                                                                                                                                                                                                                                                                         
            else:                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                kong.log.notice("Condition unvalidated")                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        except Exception as ex:                                                                                                                                                                                                                                                                                                                                                                                                                                             
            return kong.response.exit(400, "XPath routing failed" )                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        kong.log.notice("XPathRouting *** END ***")                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
#--------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                       
# This plugin handles XML content in this order:                                                                                                                                                                                                                                                                                                                                                                                                                            
# 1) Transform the XML content with XSLT                                                                                                                                                                                                                                                                                                                                                                                                                                    
# 2) Replace the value of XPath tags                                                                                                                                                                                                                                                                                                                                                                                                                                        
# 3) Check XML validity against the XSD schema (XSD SOAP and XSD API)                                                                                                                                                                                                                                                                                                                                                                                                       
#--------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                       
class Plugin(object):                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    def __init__(self, config):                                                                                                                                                                                                                                                                                                                                                                                                                                             
        self.config = config                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    #----------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                   
    # Executed for every request from a client and                                                                                                                                                                                                                                                                                                                                                                                                                          
    # before it is being proxied to the upstream service                                                                                                                                                                                                                                                                                                                                                                                                                    
    #----------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                   
    def access(self, kong: kong.kong):                                                                                                                                                                                                                                                                                                                                                                                                                                      
        kong.log.notice("access *** BEGIN ***")                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        try:                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            xmlH = Route-by-XPath(self.config)                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
            xmlH.Routing(kong)                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        except Exception as ex:                                                                                                                                                                                                                                                                                                                                                                                                                                             
            kong.log.err("XML Handling error, exception= {}".format(ex))                                                                                                                                                                                                                                                                                                                                                                                                    
            return                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        kong.log.notice("access *** END ***")                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
# add below section to allow this plugin optionally be running in a dedicated process                                                                                                                                                                                                                                                                                                                                                                                       
if __name__ == "__main__":                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    from kong_pdk.cli import start_dedicated_server                                                                                                                                                                                                                                                                                                                                                                                                                         
    start_dedicated_server("route-by-xpath", Plugin, version, priority, Schema)
